site_name: Jimmy
nav:
- Home: index.md
- blockchain:
  - Bitshare:
    - setup: blockchain/bitshare/setup.md
  - Eth:
    - setup: blockchain/eth/init_env.md
- cocos:
  - crypt: cocos/crypt.md
  - luajit-decrypt: cocos/luajit-decrypt.md
- unity:
  - tips: unity/tips.md
- mics:
  - Android Debug: mics/android-debug.md
  - Google Phone: mics/G-phone.md
  - 区块链: mics/区块链.md
  - Cross Build: mics/cross-build.md
  - Markdown: mics/markdown.md
- life:
  - health: life/health.md
theme: readthedocs

google_analytics: ['UA-127214348-1', 'auto']

markdown_extensions:
    - admonition
